// <auto-generated />
using System;
using LojaSeuManoel.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaSeuManoel.WebApi.Migrations
{
    [DbContext(typeof(LojaContext))]
    partial class LojaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.CaixaUtilizada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoCaixaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("TipoCaixaId");

                    b.ToTable("CaixasUtilizadas");
                });

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<int?>("CaixaUtilizadaId")
                        .HasColumnType("int");

                    b.Property<int>("Comprimento")
                        .HasColumnType("int");

                    b.Property<int>("Largura")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaixaUtilizadaId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.TipoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<int>("Comprimento")
                        .HasColumnType("int");

                    b.Property<int>("Largura")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposCaixa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = 30,
                            Comprimento = 80,
                            Largura = 40,
                            Nome = "Caixa 1"
                        },
                        new
                        {
                            Id = 2,
                            Altura = 80,
                            Comprimento = 40,
                            Largura = 50,
                            Nome = "Caixa 2"
                        },
                        new
                        {
                            Id = 3,
                            Altura = 50,
                            Comprimento = 60,
                            Largura = 80,
                            Nome = "Caixa 3"
                        });
                });

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 6, 1, 19, 1, 44, 369, DateTimeKind.Utc).AddTicks(2549),
                            Email = "admin",
                            Nome = "Administrador",
                            SenhaHash = "$2a$11$0lHj0TfSfm2bsUD6BHmHXeXv4bmuupS2ffftkGZnyYDlY3jT4DZWi"
                        });
                });

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.CaixaUtilizada", b =>
                {
                    b.HasOne("LojaSeuManoel.WebApi.Models.Pedido", "Pedido")
                        .WithMany("CaixasUtilizadas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojaSeuManoel.WebApi.Models.TipoCaixa", "TipoCaixa")
                        .WithMany()
                        .HasForeignKey("TipoCaixaId");

                    b.Navigation("Pedido");

                    b.Navigation("TipoCaixa");
                });

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.Produto", b =>
                {
                    b.HasOne("LojaSeuManoel.WebApi.Models.CaixaUtilizada", null)
                        .WithMany("ProdutosDaCaixa")
                        .HasForeignKey("CaixaUtilizadaId");

                    b.HasOne("LojaSeuManoel.WebApi.Models.Pedido", "Pedido")
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.CaixaUtilizada", b =>
                {
                    b.Navigation("ProdutosDaCaixa");
                });

            modelBuilder.Entity("LojaSeuManoel.WebApi.Models.Pedido", b =>
                {
                    b.Navigation("CaixasUtilizadas");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
